---
- hosts: all
  become: true
  vars:
    redis_port: 6379
    redis_databases: 1  
  tasks:
    - name: Make sure we can connect
      ping:
    - name: apt-get update 
      apt: update_cache=yes    
    - name: adding xper-hanades02 to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "192.168.142.102 xper-hanades02  xper-hanades02.hanab1.local  ts1.n00.xper-hanades02.hanab1.local"
        state: present  
    - name: Setting PasswordAuthentication yes in /etc/ssh/sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication no"
        line: "PasswordAuthentication yes"
        state: present
      notify: 
        - restart_sshd
    - name: Ensure Redis is present
      apt: pkg=redis-server state=latest        
    - name: Ensure Redis is started
      service: name=redis-server state=started enabled=yes   
    - name: Ensure git is present
      apt: name=git state=present
    - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: add repo for nodesource
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main' 
        update_cache: yes
    - name: install nodejs
      apt: name=nodejs      
    - name: Create repos directory
      file: dest=/home/vagrant/repos state=directory owner=vagrant group=vagrant    
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted      