---
- hosts: all
  become: true
  vars:
    redis_port: 6379
    redis_databases: 1  
  tasks:
    - name: Make sure we can connect
      ping:
    - name: apt-get update 
      apt: update_cache=yes    
    - name: adding xper-hanades02 to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "192.168.142.102 xper-hanades02  xper-hanades02.hanab1.local  ts1.n00.xper-hanades02.hanab1.local"
        state: present  
    - name: Setting PasswordAuthentication yes in /etc/ssh/sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication no"
        line: "PasswordAuthentication yes"
        state: present
      notify: 
        - restart_sshd
    - name: Ensure Redis is present
      apt: pkg=redis-server state=latest        
    - name: Ensure Redis is started
      service: name=redis-server state=started enabled=yes   
    - name: Ensure git is present
      apt: name=git state=present
    - name: Ensure dos2unix is present
      apt: name=dos2unix state=present      
    - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: add repo for nodesource
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main' 
        update_cache: yes
    - name: install nodejs
      apt: name=nodejs      
    - name: Create recordgo directory
      file: dest=/home/vagrant/repos/recordgo state=directory owner=vagrant group=vagrant  
    - name: Copy rgo_get_db_artifact files
      copy:
        src: ./templates/rgo_get_db_artifact
        dest: "/home/vagrant/repos/recordgo/"
        owner: vagrant
        group: vagrant
    - name: Copy rgo_get_xs files
      copy:
        src: ./templates/rgo_get_xs
        dest: "/home/vagrant/repos/recordgo/"
        owner: vagrant
        group: vagrant        
    - name: Set permissions to getdb.sh and getxs.sh
      file:
        path: "{{ item }}"
        mode: 0750
      loop:
        - /home/vagrant/repos/recordgo/rgo_get_db_artifact/getdb.sh
        - /home/vagrant/repos/recordgo/rgo_get_xs/getxs.sh
    - name: Create a symbolic link getdb to /home/vagrant/repos/recordgo/rgo_get_db_artifact/getdb.sh
      file:
        src: /home/vagrant/repos/recordgo/rgo_get_db_artifact/getdb.sh
        dest: /usr/bin/getdb
        state: link        
    - name: Create a symbolic link getxs to /home/vagrant/repos/recordgo/rgo_get_xs/getxs.sh
      file:
        src: /home/vagrant/repos/recordgo/rgo_get_xs/getxs.sh
        dest: /usr/bin/getxs
        state: link        
    - name: Declaring Ansible hosts. Writing /etc/ansible/hosts
      template: src=./templates/ansible_hosts dest=/etc/ansible/hosts
    - name: Create ssh expertone folder
      file: dest="/home/vagrant/.ssh/expertone" state=directory owner=vagrant group=vagrant
    - name: Generating SSH keys
      openssh_keypair:
        path: /home/vagrant/.ssh/expertone/xperhanades02
        type: rsa
        size: 4096
        state: present
        force: no
        owner: vagrant
        group: vagrant
    - name: Editing ssh config. Writing /home/vagrant/.ssh/config
      template: src=templates/ssh_config dest=/home/vagrant/.ssh/config owner=vagrant group=vagrant        
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted      